core/urls.py
from django.urls import path
from .views import IndexView

app_name = 'core'
urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('<str:lang_code_selected>/', IndexView.as_view(), name='language')
]

fusion/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from django.conf import settings

from fusion.settings import DEBUG

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls'))
]

if DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

core/models.py
import uuid
from django.db import models
from stdimage import StdImageField
from django.utils.translation import gettext_lazy as _


def get_file_path(_instance, filename):
    ext = filename.split('.')[-1]
    filename = f'{uuid.uuid4()}.{ext}'
    return filename


class Base(models.Model):
    created = models.DateTimeField(_('Created'), auto_now_add=True)
    modified = models.DateTimeField(_('Modified'), auto_now=True)
    active = models.BooleanField('Active?', default=True)

    class Meta:
        abstract = True


class Service(Base):
    ICON_CHOICES = (
        ('lni-cog', _('Engine')),
        ('lni-stats-up', _('Chart')),
        ('lni-users', _('User')),
        ('lni-layers', _('Design')),
        ('lni-mobile', _('Mobile')),
        ('lni-rocket', _('Rocket')),
    )
    service = models.CharField(_('Service'), max_length=100)
    description = models.TextField(_('Description'), max_length=200)
    icon = models.CharField(_('Icon'), max_length=12, choices=ICON_CHOICES)

    class Meta:
        verbose_name = _('Service')
        verbose_name_plural = _('Services')

    def __str__(self):
        return self.service


class Feature(Base):
    ICON_CHOICES = (
        ('lni-cog', _('Engine')),
        ('lni-stats-up', _('Chart')),
        ('lni-users', _('User')),
        ('lni-layers', _('Design')),
        ('lni-mobile', _('Mobile')),
        ('lni-rocket', _('Rocket')),
    )
    name = models.CharField(_('Name'), max_length=30)
    description = models.TextField(_('Description'), max_length=65)
    icon = models.CharField(_('Icon'), max_length=12, choices=ICON_CHOICES)

    class Meta:
        verbose_name = _('Feature')
        verbose_name_plural = _('Features')

    def __str__(self):
        return self.name


class Role(Base):
    role = models.CharField(_('Role'), max_length=100)

    class Meta:
        verbose_name = _('Role')
        verbose_name_plural = _('Roles')

    def __str__(self):
        return self.role


class Employee(Base):
    name = models.CharField(_('Employee'), max_length=100)
    role = models.ForeignKey('core.Role', verbose_name=_('Role'), on_delete=models.CASCADE)
    bio = models.TextField(_('Bio'), max_length=65)
    image = StdImageField(_('Image'), upload_to=get_file_path,
                          variations={
                              'thumbs':
                                  {'width': 480, 'height': 480, 'crop': True}
                          })
    facebook = models.CharField('Facebook', max_length=100, default='#')
    twitter = models.CharField('Twitter', max_length=100, default='#')
    instagram = models.CharField('Instagram', max_length=100, default='#')

    class Meta:
        verbose_name = _('Employee')
        verbose_name_plural = _('Employees')

    def __str__(self):
        return self.name

core/forms.py
from django import forms
from django.core.mail.message import EmailMessage
from django.utils.translation import gettext_lazy as _


class ContactForm(forms.Form):
    """
    Form class for sending emails from index page to contac/suport
    of the plataform
    """
    name = forms.CharField(label=_('Name'), max_length=100)
    email = forms.EmailField(label=_('Email'), max_length=100)
    subject = forms.CharField(label=_('Subject'), max_length=100)
    message = forms.CharField(label=_('Message'), widget=forms.Textarea())

    def send_mail(self):
        name = self.cleaned_data['name']
        email = self.cleaned_data['email']
        subject = self.cleaned_data['subject']
        message = self.cleaned_data['message']

        mail = EmailMessage(
            subject=subject,
            body=message,
            from_email=email,
            to=['contact@mydomain.com', ],
            headers={'Replay-to': name}
        )
        mail.send()

core/views.py
from django.contrib import messages
from django.http import request
from django.urls import reverse_lazy
from django.views.generic import FormView
from .models import Service, Employee, Feature
from .forms import ContactForm
from django.utils.translation import gettext as _
from django.utils import translation


class IndexView(FormView):
    template_name = 'core/index.html'
    form_class = ContactForm
    success_url = reverse_lazy('core:index')

    def get_context_data(self, **kwargs):
        """
        Override get_context_data() to return:
        top 6 Services
        top 6 Employee
        top 6 Features (2 querysets with 3 eachone)
        Internalization translate if selected
        """
        context = super(IndexView, self).get_context_data(**kwargs)

        context['services'] = Service.objects.order_by('?').all()[:6]
        context['employees'] = Employee.objects.all()[:6]

        # last top 3 features
        context['features_left'] = Feature.objects.order_by('-modified').all()[:3]

        # last top 4-6 features
        context['features_right'] = Feature.objects.order_by('-modified').all()[3:6]
        context['available_languages'] = ['en', 'pt-br']

        # get language from browser request
        lang_browser = self.request.LANGUAGE_CODE

        # get language code if selected
        lang_code_selected = context['view'].kwargs.get('lang_code_selected', None)

        if lang_code_selected:
            translation.activate(lang_code_selected)

            # set lang_browser value to template attribute lang="" after translation
            context['lang_browser'] = lang_code_selected

        else:
            translation.activate(lang_browser)

            # set lang_browser value to template attribute lang="" after translation
            context['lang_browser'] = lang_browser

        return context

    def form_valid(self, form, *args, **kwargs):
        form.send_mail()
        messages.success(self.request, _('Email successfully sent'))
        return super(IndexView, self).form_valid(form, *args, **kwargs)

    def form_invalid(self, form, *args, **kwargs):
        messages.error(self.request, _('Fail sending email'))
        return super(IndexView, self).form_invalid(form, *args, **kwargs)

core/templates/core/about.html
{% load i18n %}
{% load static %}
<div class="about-area section-padding bg-gray">
      <div class="container">
        <div class="row">
          <div class="col-lg-6 col-md-12 col-xs-12 info">
            <div class="about-wrapper wow fadeInLeft" data-wow-delay="0.3s">
              <div>
                <div class="site-heading">
                  <p class="mb-3">{% trans 'Statistics' %}</p>
                  <h2 class="section-title">{% trans 'Detailed Statistics of your Company' %}</h2>
                </div>
                <div class="content">
                  <p>
                    {% trans 'Praesent imperdiet, tellus et euismod euismod, risus lorem euismod erat, at finibus neque odio quis metus. Donec vulputate arcu quam. Morbi quis tincidunt ligula. Sed rutrum tincidunt pretium. Mauris auctor, purus a pulvinar fermentum, odio dui vehicula lorem, nec pharetra justo risus quis mi. Ut ac ex sagittis, viverra nisl vel, rhoncus odio.' %}
                  </p>
                  <a href="#" class="btn btn-common mt-3">{% trans 'Read More' %}</a>
                </div>
              </div>
            </div>
          </div>
          <div class="col-lg-6 col-md-12 col-xs-12 wow fadeInRight" data-wow-delay="0.3s">
            <img class="img-fluid" src="{% static 'core/img/about/img-1.png' %}" alt="" >
          </div>
        </div>
      </div>
    </div>

core/templates/core/base.html
 <!DOCTYPE html>
 {% load i18n %}
 {% load static %}
<html lang="{{ lang_browser }}">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>Fusion</title>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'core/css/bootstrap.min.css' %}">
    <!-- Icon -->
    <link rel="stylesheet" href="{% static 'core/fonts/line-icons.css' %}">
    <!-- Owl carousel -->
    <link rel="stylesheet" href="{% static 'core/css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'core/css/owl.theme.css' %}">

    <!-- Animate -->
    <link rel="stylesheet" href="{% static 'core/css/animate.css' %}">
    <!-- Main Style -->
    <link rel="stylesheet" href="{% static 'core/css/main.css' %}">
    <!-- Responsive Style -->
    <link rel="stylesheet" href="{% static 'core/css/responsive.css' %}">

  </head>
  <body>

    <!-- Header Area wrapper Starts -->
    <header id="header-wrap">
      <!-- Navbar Start -->
      <nav class="navbar navbar-expand-md bg-inverse fixed-top scrolling-navbar">
        <div class="container">
          <!-- Brand and toggle get grouped for better mobile display -->
          <a href="{% url 'core:index' %}" class="navbar-brand"><img src="{% static 'core/img/logo.png' %}" alt=""></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <i class="lni-menu"></i>
          </button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto w-100 justify-content-end clearfix">
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'core:index' %}">
                  Home
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#services">
                  Services
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#team">
                  Team
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#pricing">
                  Pricing
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#testimonial">
                  Testimonial
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#contact">
                  Contact
                </a>
              </li>

            </ul>
            <ul class="navbar-nav mr-auto w-100 justify-content-end clearfix">
                {% for lang in available_languages %}
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'core:language' lang %}">
                      {{ lang }}
                    </a>

                  </li>
                {% endfor %}
            </ul>
          </div>
        </div>
      </nav>
      <!-- Navbar End -->
        {% block content %}

        {% endblock %}

    <!-- Go to Top Link -->
    <a href="#" class="back-to-top">
    	<i class="lni-arrow-up"></i>
    </a>

    <!-- Preloader -->
    <div id="preloader">
      <div class="loader" id="loader-1"></div>
    </div>
    <!-- End Preloader -->

    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="{% static 'core/js/jquery-min.js' %}"></script>
    <script src="{% static 'core/js/popper.min.js' %}"></script>
    <script src="{% static 'core/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'core/js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'core/js/wow.js' %}"></script>
    <script src="{% static 'core/js/jquery.nav.js' %}"></script>
    <script src="{% static 'core/js/scrolling-nav.js' %}"></script>
    <script src="{% static 'core/js/jquery.easing.min.js' %}"></script>
    <script src="{% static 'core/js/main.js' %}"></script>
    <script src="{% static 'core/js/form-validator.min.js' %}"></script>
    <script src="{% static 'core/js/contact-form-script.min.js' %}"></script>

  </body>
</html>

core/templates/core/call.html
{% load static %}
   <section id="cta" class="section-padding">
      <div class="container">
        <div class="row">
          <div class="col-lg-6 col-md-6 col-xs-12 wow fadeInLeft" data-wow-delay="0.3s">
            <div class="cta-text">
              <h4>Get 30 days free trial</h4>
              <p>Praesent imperdiet, tellus et euismod euismod, risus lorem euismod erat, at finibus neque odio quis metus. Donec vulputate arcu quam. </p>
            </div>
          </div>
          <div class="col-lg-6 col-md-6 col-xs-12 text-right wow fadeInRight" data-wow-delay="0.3s">
            </br><a href="#" class="btn btn-common">Register Now</a>
          </div>
        </div>
      </div>
    </section>

core/templates/core/contact.html
{% load static %}
<section id="contact" class="section-padding bg-gray">
      <div class="container">
        <div class="section-header text-center">
          <h2 class="section-title wow fadeInDown" data-wow-delay="0.3s">Countact Us</h2>
          <div class="shape wow fadeInDown" data-wow-delay="0.3s"></div>
        </div>
        <div class="row contact-form-area wow fadeInUp" data-wow-delay="0.3s">
          <div class="col-lg-7 col-md-12 col-sm-12">
            <div class="contact-block">
              <form id="form_contact" method="POST" action="{% url 'core:index' %}" autocomplete="off">
                  {% csrf_token %}
                <div class="row">
                  <div class="col-md-6">
                    <div class="form-group">
                      <input id="name" name="name" type="text" class="form-control"  placeholder="Name" required data-error="Please enter your name">
                      <div class="help-block with-errors"></div>
                    </div>
                  </div>
                  <div class="col-md-6">
                    <div class="form-group">
                      <input id="email" name="email" type="email" placeholder="Email" class="form-control"  required data-error="Please enter your email">
                      <div class="help-block with-errors"></div>
                    </div>
                  </div>
                   <div class="col-md-12">
                    <div class="form-group">
                      <input id="subject" name="subject" type="text" placeholder="Subject" class="form-control" required data-error="Please enter your subject">
                      <div class="help-block with-errors"></div>
                    </div>
                  </div>
                  <div class="col-md-12">
                    <div class="form-group">
                      <textarea id="message" name="message" class="form-control" placeholder="Your Message" rows="7" data-error="Write your message" required></textarea>
                      <div class="help-block with-errors"></div>
                    </div>
                    <div class="submit-button text-left">
                      <button class="btn btn-common" id="form-submit" type="submit">Send Message</button>
                      <div id="msgSubmit" class="h3 text-center hidden"></div>
                      <div class="clearfix"></div>
                    </div>
                  </div>
                </div>
              </form>
            </div>
          </div>
          <div class="col-lg-5 col-md-12 col-xs-12">
            <div class="map">
<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3658.9221978767723!2d-46.35025858502341!3d-23.4993116847137!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x94ce7b43881e4717%3A0xf103e4ae1a85a9cf!2sR.%20Minas%20Gerais%2C%20170%20-%20Morro%20Branco%2C%20Itaquaquecetuba%20-%20SP%2C%2008572-450!5e0!3m2!1spt-BR!2sbr!4v1584227010023!5m2!1spt-BR!2sbr" width="335" height="380" frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>            </div>
          </div>
        </div>
      </div>
    </section>

core/templates/core/features.html
{% load i18n %}
{% load static %}
<section id="features" class="section-padding">
      <div class="container">
        <div class="section-header text-center">
          <h2 class="section-title wow fadeInDown" data-wow-delay="0.3s">{% trans 'Awesome Features' %}</h2>
          <div class="shape wow fadeInDown" data-wow-delay="0.3s"></div>
        </div>
        <div class="row">
          <div class="col-lg-4 col-md-12 col-sm-12 col-xs-12">
            <div class="content-left">
                  {% for f in features_left %}
                    {% if f.active %}
                    <div class="box-item wow fadeInLeft" data-wow-delay="0.3s">
                      <span class="icon">
                        <i class="{{ f.icon }}"></i>
                      </span>
                      <div class="text">
                        <h4>{{ f.name }}</h4>
                        <p>{{ f.description }}</p>
                      </div>
                    </div>
                    {% else %}
                    <div class="box-item wow fadeInLeft" data-wow-delay="0.3s">
                          <span class="icon">
                            <i class="{{ f.icon }}"></i>
                          </span>
                          <div class="text">
                            <h4>{{ f.name }}</h4>
                            <p>Unavailable at the moment. It'll be back soon. </p>
                          </div>
                        </div>
                    {% endif %}
              {% endfor %}
            </div>
          </div>
          <div class="col-lg-4 col-md-12 col-sm-12 col-xs-12">
            <div class="show-box wow fadeInUp" data-wow-delay="0.3s">
              <img src="{% static 'core/img/feature/intro-mobile.png' %}" alt="">
            </div>
          </div>
          <div class="col-lg-4 col-md-12 col-sm-12 col-xs-12">
            <div class="content-right">
               {% for f in features_right %}
                    {% if f.active %}
                    <div class="box-item wow fadeInLeft" data-wow-delay="0.3s">
                      <span class="icon">
                        <i class="{{ f.icon }}"></i>
                      </span>
                      <div class="text">
                        <h4>{{ f.name }}</h4>
                        <p>{{ f.description }}</p>
                      </div>
                    </div>
                    {% else %}
                    <div class="box-item wow fadeInLeft" data-wow-delay="0.3s">
                          <span class="icon">
                            <i class="{{ f.icon }}"></i>
                          </span>
                          <div class="text">
                            <h4>{{ f.name }}</h4>
                            <p>Unavailable at the moment. It'll be back soon. </p>
                          </div>
                        </div>
                    {% endif %}
              {% endfor %}
            </div>
          </div>
        </div>
      </div>
    </section>

core/templates/core/footer.html
{% load static %}
<footer id="footer" class="footer-area section-padding">
      <div class="container">
        <div class="container">
          <div class="row">
            <div class="col-lg-3 col-md-6 col-sm-6 col-xs-6 col-mb-12">
              <div class="widget">
                <h3 class="footer-logo"><img src="{% static 'core/img/logo.png' %}" alt=""></h3>
                <div class="textwidget">
                  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque lobortis tincidunt est, et euismod purus suscipit quis.</p>
                </div>
                <div class="social-icon">
                  <a class="facebook" href="#"><i class="lni-facebook-filled"></i></a>
                  <a class="twitter" href="#"><i class="lni-twitter-filled"></i></a>
                  <a class="instagram" href="#"><i class="lni-instagram-filled"></i></a>
                  <a class="linkedin" href="#"><i class="lni-linkedin-filled"></i></a>
                </div>
              </div>
            </div>
            <div class="col-lg-3 col-md-6 col-sm-12 col-xs-12">
              <h3 class="footer-titel">Products</h3>
              <ul class="footer-link">
                <li><a href="#">Tracking</a></li>
                <li><a href="#">Application</a></li>
                <li><a href="#">Resource Planning</a></li>
                <li><a href="#">Enterprise</a></li>
                <li><a href="#">Employee Management</a></li>
              </ul>
            </div>
            <div class="col-lg-3 col-md-6 col-sm-12 col-xs-12">
              <h3 class="footer-titel">Resources</h3>
              <ul class="footer-link">
                <li><a href="#">Payment Options</a></li>
                <li><a href="#">Fee Schedule</a></li>
                <li><a href="#">Getting Started</a></li>
                <li><a href="#">Identity Verification</a></li>
                <li><a href="#">Card Verification</a></li>
              </ul>
            </div>
            <div class="col-lg-3 col-md-6 col-sm-12 col-xs-12">
              <h3 class="footer-titel">Contact</h3>
              <ul class="address">
                <li>
                  <a href="#"><i class="lni-map-marker"></i> 105 Madison Avenue - <br> Third Floor New York, NY 10016</a>
                </li>
                <li>
                  <a href="#"><i class="lni-phone-handset"></i> P: +84 846 250 592</a>
                </li>
                <li>
                  <a href="#"><i class="lni-envelope"></i> E: contact@uideck.com</a>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
      <div id="copyright">
        <div class="container">
          <div class="row">
            <div class="col-md-12">
              <div class="copyright-content">
                <p>Copyright © 2020 <a rel="nofollow" href="https://uideck.com">UIdeck</a> All Right Reserved</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </footer>

core/templates/core/hero.html
{% load i18n %}
{% load static %}
<div id="hero-area" class="hero-area-bg">
    {% if messages %}
        {% for message in messages %}
        <div class="container">
             <div class="alert alert-{{ message.tags}} alert-dismissible fade show" role="alert">
             {{ message }}
             <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
             </div>
        </div>
        {% endfor %}
    {% endif %}
    <div class="container">
      <div class="row">
        <div class="col-lg-7 col-md-12 col-sm-12 col-xs-12">
          <div class="contents">
            <h2 class="head-title">{% trans 'App, Business & SaaS' %}</h2>
              <p class="h2">{% trans 'Landing Page' %}</p>
            <p>{% trans 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Rem repellendus quasi fuga nesciunt dolorum nulla magnam veniam sapiente, fugiat! fuga nesciunt dolorum nulla magnam veniam sapiente, fugiat!' %}</p>
            <div class="header-button">
              <a href="#" class="btn btn-common">{% trans 'Download Now' %}</i></a>
              <a href="#" class="btn btn-border video-popup">{% trans 'Learn More' %} </i></a>
            </div>
          </div>
        </div>
        <div class="col-lg-5 col-md-12 col-sm-12 col-xs-12">
          <div class="intro-img">
            <img class="img-fluid" src="{% static 'core/img/intro-mobile.png' %}" alt="">
          </div>
        </div>
      </div>
    </div>
</div>
<!-- Hero Area End -->
</header>

core/templates/core/index.html
{% extends 'core/base.html' %}
{% load static %}
{% block content %}
      <!-- Hero Area Start -->
    {% include 'core/hero.html' %}
    <!-- Header Area wrapper End -->

    <!-- Services Section Start -->
    {% include 'core/services.html' %}
    <!-- Services Section End -->

    <!-- About Section start -->
    {% include 'core/about.html' %}
    <!-- About Section End -->

    <!-- Features Section Start -->
    {% include 'core/features.html' %}
    <!-- Features Section End -->

    <!-- Team Section Start -->
    {% include 'core/team.html' %}
    <!-- Team Section End -->

    <!-- Pricing section Start -->
    {% include 'core/prices.html' %}
    <!-- Pricing Table Section End -->

    <!-- Testimonial Section Start -->
    {% include 'core/testimonials.html' %}
    <!-- Testimonial Section End -->

    <!-- Call To Action Section Start -->
    <!--    {% include 'core/call.html' %}  -->
    <!-- Call To Action Section Start -->

    <!-- Contact Section Start -->
    {% include 'core/contact.html' %}
    <!-- Contact Section End -->

    <!-- Footer Section Start -->
    {% include 'core/footer.html' %}
    <!-- Footer Section End -->

{% endblock %}

core/templates/core/prices.html
<section id="pricing" class="section-padding">
      <div class="container">
        <div class="section-header text-center">
          <h2 class="section-title wow fadeInDown" data-wow-delay="0.3s">Pricing</h2>
          <div class="shape wow fadeInDown" data-wow-delay="0.3s"></div>
        </div>
        <div class="row">
          <div class="col-lg-4 col-md-6 col-xs-12">
            <div class="table wow fadeInLeft" data-wow-delay="1.2s">
              <div class="icon-box">
                <i class="lni-package"></i>
              </div>
              <div class="pricing-header">
                <p class="price-value">$10<span> /mo</span></p>
              </div>
              <div class="title">
                <h3>Pro</h3>
              </div>
              <ul class="description">
                <li>1 user</li>
                <li>10 GB storage</li>
                <li>Email support</li>
                <li>Lifetime updates</li>
              </ul>
              <button class="btn btn-common">Buy Now</button>
            </div>
          </div>
          <div class="col-lg-4 col-md-6 col-xs-12 active">
            <div class="table wow fadeInUp" id="active-tb" data-wow-delay="1.2s">
              <div class="icon-box">
                <i class="lni-drop"></i>
              </div>
              <div class="pricing-header">
                <p class="price-value">$35<span> /mo</span></p>
              </div>
              <div class="title">
                <h3>Plus</h3>
              </div>
              <ul class="description">
                <li>10 user</li>
                <li>30 GB storage</li>
                <li>Priority email support</li>
                <li>Lifetime updates</li>
              </ul>
              <button class="btn btn-common">Buy Now</button>
           </div>
          </div>
          <div class="col-lg-4 col-md-6 col-xs-12">
            <div class="table wow fadeInRight" data-wow-delay="1.2s">
              <div class="icon-box">
                <i class="lni-star"></i>
              </div>
              <div class="pricing-header">
                <p class="price-value">$150<span> /mo</span></p>
              </div>
              <div class="title">
                <h3>Premium</h3>
              </div>
              <ul class="description">
                <li>Unlimited users</li>
                <li>Unlimited storage</li>
                <li>24/7 support</li>
                <li>Lifetime updates</li>
              </ul>
              <button class="btn btn-common">Buy Now</button>
            </div>
          </div>
        </div>
      </div>
    </section>

core/templates/core/services.html
{% load i18n %}
{% load static %}
<section id="services" class="section-padding">
      <div class="container">
        <div class="section-header text-center">
          <h2 class="section-title wow fadeInDown" data-wow-delay="0.3s">{% trans 'Our Services' %}</h2>
          <div class="shape wow fadeInDown" data-wow-delay="0.3s"></div>
        </div>
        <div class="card-deck">
          {% if services %}
            {% for s in services %}
            <!-- Services item -->
              {% if s.active %}
              <div class="col-md-6 col-lg-4 col-xs-12">
                <div class="services-item wow fadeInRight h-100" data-wow-delay="0.3s">
                  <div class="icon">
                    <i class="{{ s.icon }}"></i>
                  </div>
                  <div class="services-content">
                    <h3><a href="#">{{ s.service }}</a></h3>
                    <p>{{ s.description }}</p>
                  </div>
                </div>
              </div>
              {% else %}
              <div class="col-md-6 col-lg-4 col-xs-12">
                <div class="services-item wow fadeInRight bg-light h-100" data-wow-delay="0.3s">
                  <div class="icon">
                    <i class="lni-cog"></i>
                  </div>
                  <div class="services-content">
                    <h3><a>{{ s.service }}</a></h3>
                  <div class="my-5">
                    <p>{% trans "Unavaliable at the moment. It'll be available soon. " %}</p>
                  </div>
                  </div>
                </div>
              </div>
              {% endif %}
            {% endfor %}
          {% else%}
          <div class="alert alert-secondary" role="alert">
              {% trans 'Under construction, ' %}<a href="#" class="alert-link">{% trans 'you can go back here. ' %}</a>{% trans 'Sorry for this.' %}
          </div>
          {% endif%}
        </div>
      </div>
    </section>

core/templates/core/team.html
{% load i18n %}
{% load static %}
<section id="team" class="section-padding bg-gray">
      <div class="container">
        <div class="section-header text-center">
          <h2 class="section-title wow fadeInDown" data-wow-delay="0.3s">{% trans 'Meet our team' %}</h2>
          <div class="shape wow fadeInDown" data-wow-delay="0.3s"></div>
        </div>
        <div class="row">
            {% for e in employees %}
              {% if e.active %}
              <!-- Team Item Starts -->
            <div class="col-md-6 col-sm-12 my-2">
              <div class="card border-0 shadow">
                <div class="row card-body">
                  <div class="col-sm-4 col-md-4 col-lg-4">
                  <img class="img-fluid" src="{{ e.image.url }}" alt="" style="max-height: 200px;">
                  </div>

                <div class="col-sm-8 col-md-8 col-lg-8">
                    <p class="h5 text-bold card-title">{{ e.name }}</p>
                    <p>{{ e.role }}</p>
                    <p>{{ e.bio }}</p>
                  <div class="">
                   <a href="{{ e.facebook }}"><i class="btn btn-link lni-facebook-filled" aria-hidden="true"></i></a>
                   <a href="{{ e.twitter }}"><i class="lni-twitter-filled" aria-hidden="true"></i></a>
                    <a href="{{ e.instagram }}"><i class="lni-instagram" aria-hidden="true"></i></a>
                </div>
                </div>
                </div>
              </div>
              </div>
              <!-- Team Item Ends -->
            {% else %}

            {% endif %}
          {% endfor %}
          </div>
      </div>
    </section>